# Server
server.port=8888

# Data files
scoresheet.players.url=https://www.scoresheet.com/FOR_WWW/BL_Players_2026.tsv
scoresheet.projections.dir=.

# Thymeleaf
spring.thymeleaf.cache=false

# Leagues configuration
scoresheet.leagues[0].id=wP_AL803
scoresheet.leagues[0].name=wP-AL803

scoresheet.leagues[1].id=BL_Final_Table
scoresheet.leagues[1].name=BL Final Table

scoresheet.leagues[2].id=BL_DwMurphy
scoresheet.leagues[2].name=BL DwMurphy

scoresheet.leagues[3].id=BL_DBJ
scoresheet.leagues[3].name=BL DBJ

scoresheet.leagues[4].id=BL_Kings
scoresheet.leagues[4].name=BL Kings

scoresheet.leagues[5].id=AL_Willard
scoresheet.leagues[5].name=AL Willard

scoresheet.leagues[6].id=NL_Willard
scoresheet.leagues[6].name=NL Willard
